[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    #
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
    'lib'
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    #
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'dn404-adjustable/=lib/dn404-adjustable/src/',
    'solady/=lib/dn404-adjustable/lib/solady/src/',
]

[rpc_endpoints]
zksync-sepolia="https://sepolia.era.zksync.dev"
amoy-testnet="https://polygon-amoy-bor-rpc.publicnode.com"
base-sepolia="https://sepolia.base.org"
polygon="${POL_RPC_URL}"
base="https://mainnet.base.org"
zksync="https://mainnet.era.zksync.io"
lens = "https://rpc.lens.dev"

[etherscan]
zksyncTestnet = { key = "${ZK_ETHERSCAN_API_KEY}", url = "https://api-sepolia-era.zksync.network/api", chain = 300 }
zksync = { key = "${ZK_ETHERSCAN_API_KEY}", url = "https://api-era.zksync.network/api", chain = 324 }
polygon = { key = "${POL_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api", chain = 137 }